VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Logger"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'---------------------------------------------------------------------------------------
' Author    : Chad Milando
' Copyright : Copyright 2020, 2021, Trustees of Boston University.
'             All rights reserved.
' License   : This software is provided under the terms of the
'             SOFTWARE EVALUATION LICENSE AGREEMENT as detailed in
'             the "license.txt" file in source directory.
'---------------------------------------------------------------------------------------
'@Folder("VBAProject")
